project:
  type: website
  output-dir: docs

website:
  title: "Colton Gearhart"
  search: 
    location: navbar
    type: textbox
  favicon: "files/images/favicon.png"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Courses
        href: courses.qmd
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd
    right:
      - icon: github
        href: https://github.com/coltongearhart
      - icon: linkedin
        href: https://www.linkedin.com/in/coltongearhart/
      - icon: briefcase
        href: https://www.bsu.edu/academics/collegesanddepartments/math/about/facultyandstaff/faculty/gearhartcolton
  page-footer:
    center: |
      [Contact Colton Gearhart](mailto:gearhart.colton.work@gmail.com)
    left: |
      Made with [Quarto](https://quarto.org/)
    right: |
      [Github Repo](https://github.com/coltongearhart/myportfolio)
format:
  html:
    theme:
      light: flatly
      dark: [flatly, theme_dark_custom.scss]
    highlight-style: github

